# Generated by Django 4.2.3 on 2024-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
