# Generated by Django 4.2.3 on 2024-12-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_availability_alter_product_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
    ]
